version: '3.9'

services:
  api:
    container_name: api
    build: .
    env_file: .env
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload --log-level warning
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 15
    ports:
      - 127.0.0.1:5432:5432

  migrate:
    container_name: migrate
    build: .
    env_file: .env
    healthcheck:
      test: "exit 0"
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head
      
volumes:
  postgres_data:
